; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=5
lib_deps = 
	m5stack/M5Stack@^0.4.2
	milesburton/DallasTemperature@^3.11.0
	https://github.com/knolleary/pubsubclient.git
	https://github.com/sparkfun/SparkFun_SCD30_Arduino_Library.git
	https://github.com/RobTillaart/SHT31.git
	https://github.com/enjoyneering/HTU2xD_SHT2x_Si70xx.git
	https://github.com/climateguard/RadSens.git
