; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; драйвера к едущим датчикам-
;    robtillaart/SHT4x @ ^0.3.0
;    sparkfun/SparkFun TMP117 Arduino Library @ ^1.0.3
;    sensirion/arduino-sps @ ^1.1.2

[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=5
lib_deps = 
	m5stack/M5Stack@^0.4.2
	milesburton/DallasTemperature@^3.11.0
	knolleary/PubSubClient@^2.8
	https://github.com/sparkfun/SparkFun_SCD30_Arduino_Library.git
	robtillaart/SHT31@^0.5.3
	;climateguard/ClimateGuard RadSens@^1.1.3
	finitespace/BME280 @ ^3.0.0
	;https://github.com/devxplained/HTU21D-Sensor-Library.git
	robtillaart/SHT2x@^0.5.5
